server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

logging:
  config: classpath:log4j2.properties

app:
  env:
    yarnAddress: http://localhost
    yarnBackupAddress: http://localhost
    bdpopsAddress: http://localhost
    hdfsAddress: http://localhost

  job:
    queue: default
    maxMaps: 1000
    mapBandwidth: 40